### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by mvrk69** [H4cK3dR4Du/LunusBPS#7]
Hi,

I'm getting this error when i try to run it:

python main.py
Traceback (most recent call last):
  File "/home/user/Downloads/main.py", line 80, in <module>
    ui()
  File "/home/user/Downloads/main.py", line 63, in ui
    ctypes.windll.kernel32.SetConsoleTitleW(f"[ LunusBPS ] By H4cK3dR4Du & 452b | Y'all love H4cK3dR4Du's and 452b's feds ❤️")
    ^^^^^^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'windll'

Is the tool only for Windows? 
Anyway to make it work in Linux?

**Comment by Incasat0r** [comment]
Same

**Comment by cyberhell-cpu** [comment]
Same here
